### ISSUE TITLE
I use the 01_GMM-UBM_system_with_ALIZE3.0 example

### ISSUE THREAD

**Issue by sunjunlishi** [ALIZE-Speaker-Recognition/LIA_RAL#1]
EnergyDetector  --config cfg/EnergyDetector_SPro.cfg --inputFeatureFilename data/data.lst --featureFilesPath  data/prm/  --labelFilesPath  data/lbl/
i have aproblem that
![xg22 s0e2b5ctri0qy7005](https://cloud.githubusercontent.com/assets/11845664/19913510/30a59258-a0de-11e6-9fad-b9675ff332a0.png)
![mjptem6rl7dk_ cvd 6t](https://cloud.githubusercontent.com/assets/11845664/19913524/526e8f02-a0de-11e6-9ba8-ef1981e75d55.png)

**Comment by jfb84** [comment]
Hello 

By using verboseLevel and/or debug options, and by redirecting the standard output into a file, you could send a text with the syssteem outputs. Easier... 
We need also the description of the problem and the configuration file of EnergyDetector. 

It seems to me that there is no model adaptation. Look at the options to adapt means, weights and cov (meanAdapt==true ...) 

Best 
JF 




De: "sunjunlishi" <notifications@github.com> 
À: "ALIZE-Speaker-Recognition/LIA_RAL" <LIA_RAL@noreply.github.com> 
Envoyé: Mercredi 2 Novembre 2016 02:25:54 
Objet: [ALIZE-Speaker-Recognition/LIA_RAL] I use the 01_GMM-UBM_system_with_ALIZE3.0 example (#1) 



EnergyDetector --config cfg/EnergyDetector_SPro.cfg --inputFeatureFilename data/data.lst --featureFilesPath data/prm/ --labelFilesPath data/lbl/ 
i have aproblem that 




— 
You are receiving this because you are subscribed to this thread. 
Reply to this email directly, view it on GitHub , or mute the thread . 


-- 
______________________________________________________________________ 
Jean-Francois BONASTRE 
Directeur du LIA 
LIA/CERI Université d'Avignon 
Tel: +33/0 490843514 
directeur-lia@univ-avignon.fr 
______________________________________________________________________

**Comment by sunjunlishi** [comment]
oh,it works,its my problem;I change the 'sfbcep.exe',it works,thanks.
![3 q 8t1_ wr6vt 2 76 g e](https://cloud.githubusercontent.com/assets/11845664/19995060/b80fc680-a28e-11e6-960a-bc9c0f32aede.png)
