### ISSUE TITLE
Alize support Speaker Verification 

### ISSUE THREAD

**Issue by javenosa** [ALIZE-Speaker-Recognition/LIA_RAL#6]
Hello,

Alize support text dependet speaker verification?

Something like passphrase validations.

Thanks

**Comment by jfb84** [comment]
Hi 
There is all the needed parts inside ALIZE to do that. 
But as far as I know there is no "official" high level tool in the toolkit. 
You could see Anthony Larcher PhD and papers for example 
Larcher, A., Bonastre, J. F., & Mason, J. S. (2008, September). Reinforced temporal structure information for embedded utterance-based speaker recognition. In Interspeech (pp. 371-374). 
Larcher, A., Bonastre, J. F., & Mason, J. S. (2013). Reinforced temporal structure of acoustic models for speaker recognition. Digital Signal Processing , 23 (6), 1910-1917. 
(and contact him!) 
BEst 
JF 



De: "javenosa" <notifications@github.com> 
À: "ALIZE-Speaker-Recognition/LIA_RAL" <LIA_RAL@noreply.github.com> 
Cc: "Subscribed" <subscribed@noreply.github.com> 
Envoyé: Jeudi 8 Juin 2017 02:35:32 
Objet: [ALIZE-Speaker-Recognition/LIA_RAL] Alize support Speaker Verification (#6) 



Hello, 

Alize support text dependet speaker verification? 

Something like passphrase validations. 

Thanks 

— 
You are receiving this because you are subscribed to this thread. 
Reply to this email directly, view it on GitHub , or mute the thread . 



-- 
______________________________________________________________________ 
Jean-Francois BONASTRE 
Directeur du LIA 
LIA/CERI Université d'Avignon 
Tel: +33/0 490843514 
directeur-lia@univ-avignon.fr 
______________________________________________________________________
